spring.application.name=demo

# QUAN TRỌNG
server.port=80

# Tăng tốc startup
spring.main.lazy-initialization=true
spring.boot.autoconfigure.condition.timeout=300

# Giảm log nếu không cần
logging.level.org.springframework=ERROR
logging.level.com.zaxxer.hikari=ERROR

# Nếu có database
spring.datasource.hikari.maximum-pool-size=5